config/routes.rb
Tueslets::Application.routes.draw do
  resources :events

  resources :planners

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :description, :loc1, :loc2, :loc3, :loc4, :time1, :time2, :time3, :time4, :title
end

app/models/planner.rb
class Planner < ActiveRecord::Base
  attr_accessible :email, :name, :password_digest, :phone, :zip
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.json
  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/planners_controller.rb
class PlannersController < ApplicationController
  # GET /planners
  # GET /planners.json
  def index
    @planners = Planner.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @planners }
    end
  end

  # GET /planners/1
  # GET /planners/1.json
  def show
    @planner = Planner.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @planner }
    end
  end

  # GET /planners/new
  # GET /planners/new.json
  def new
    @planner = Planner.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @planner }
    end
  end

  # GET /planners/1/edit
  def edit
    @planner = Planner.find(params[:id])
  end

  # POST /planners
  # POST /planners.json
  def create
    @planner = Planner.new(params[:planner])

    respond_to do |format|
      if @planner.save
        format.html { redirect_to @planner, notice: 'Planner was successfully created.' }
        format.json { render json: @planner, status: :created, location: @planner }
      else
        format.html { render action: "new" }
        format.json { render json: @planner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /planners/1
  # PUT /planners/1.json
  def update
    @planner = Planner.find(params[:id])

    respond_to do |format|
      if @planner.update_attributes(params[:planner])
        format.html { redirect_to @planner, notice: 'Planner was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @planner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /planners/1
  # DELETE /planners/1.json
  def destroy
    @planner = Planner.find(params[:id])
    @planner.destroy

    respond_to do |format|
      format.html { redirect_to planners_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/planners_helper.rb
module PlannersHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<!--   <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :loc1 %><br />
    <%= f.text_field :loc1 %>
  </div>
  <div class="field">
    <%= f.label :loc2 %><br />
    <%= f.text_field :loc2 %>
  </div>
  <div class="field">
    <%= f.label :loc3 %><br />
    <%= f.text_field :loc3 %>
  </div>
  <div class="field">
    <%= f.label :loc4 %><br />
    <%= f.text_field :loc4 %>
  </div>
  <div class="field">
    <%= f.label :time1 %><br />
    <%= f.time_select :time1 %>
  </div>
  <div class="field">
    <%= f.label :time2 %><br />
    <%= f.time_select :time2 %>
  </div>
  <div class="field">
    <%= f.label :time3 %><br />
    <%= f.time_select :time3 %>
  </div>
  <div class="field">
    <%= f.label :time4 %><br />
    <%= f.time_select :time4 %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
 -->

/////////////////////
<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
<head>

  <!-- Basic Page Needs
  ================================================== -->
  <meta charset="utf-8">
  <title>Let's Brunch</title>
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Mobile Specific Metas
  ================================================== -->
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

  <!-- CSS
  ================================================== -->
  <link rel="stylesheet" href="stylesheets/skeleton.css">
  <link rel="stylesheet" href="stylesheets/layout.css">
  <link rel="stylesheet" href="stylesheets/custom.css">

<%= stylesheet_link_tag "base", "custom" %>

  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

  <!-- Favicons
  ================================================== -->
  <link rel="shortcut icon" href="images/favicon.ico">
  <link rel="apple-touch-icon" href="images/apple-touch-icon.png">
  <link rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png">

</head>
  <body>

    <header class="container sixteen columns" style="margin-top: 80px;">
      <!-- <h1>Let's </h1> -->

      <hr/>
    </header>

  	<div class="container"> 

      <h4>Give your guests up to 4 location options, or</h4>
      <h4>Give your guests up to 4 time options</h4>

      <form>
        <!-- Label and text input -->


	 <%= f.label :title %><br />
	    <%= f.text_field :title %>
	  </div>
	  <div class="field">
	    <%= f.label :loc1 %><br />
	    <%= f.text_field :loc1 %>
	  </div>
	  <div class="field">
	    <%= f.label :loc2 %><br />
	    <%= f.text_field :loc2 %>
	  </div>
	  <div class="field">
	    <%= f.label :loc3 %><br />
	    <%= f.text_field :loc3 %>
	  </div>
	  <div class="field">
	    <%= f.label :loc4 %><br />
	    <%= f.text_field :loc4 %>
	  </div>
	  <div class="field">
	    <%= f.label :time1 %><br />
	    <%= f.time_select :time1 %>
	  </div>
	  <div class="field">
	    <%= f.label :time2 %><br />
	    <%= f.time_select :time2 %>
	  </div>
	  <div class="field">
	    <%= f.label :time3 %><br />
	    <%= f.time_select :time3 %>
	  </div>
	  <div class="field">
	    <%= f.label :time4 %><br />
	    <%= f.time_select :time4 %>
	  </div>
	  <div class="field">
	    <%= f.label :description %><br />
	    <%= f.text_area :description %>
	  </div>
	  <div class="actions">
	    <%= f.submit %>
	  </div>









<!-- 
        <label for="loc1">1.</label>
        <input type="text" id="loc1" name="loc1" value="Bongo Room" required>
        <label for="loc2">2.</label> 
        <input type="text" id="loc2" name="loc2" value="Toast" required>
        <label for="loc3">3.</label>
        <input type="text" id="loc3" name="loc3" value="Batter 'n' Berries">
        <label for="loc4">4.</label>
        <input type="text" id="loc3" name="loc4" value="Golden Apple">

      <div class="row">
      <h4> Beginning time range</h4>
        
        <label for="hr"></label>
        <select class="four columns add-bottom" required id="hr" name="startHr">
          <option value="1">1</option>
          <option value="2">2</option>
          <option value="3">3</option>
          <option value="4">4</option>
          <option value="5">5</option>
          <option value="6">6</option>
          <option value="7">7</option>
          <option value="8">8</option>
          <option value="9">9</option>
          <option value="10">10</option>
          <option value="11">11</option>
          <option value="12">12</option>
        </select>
        <select class="four columns add-bottom" required name="startMin">
          <option value="00">00</option>
          <option value="15">15</option>
          <option value="30">30</option>
          <option value="45">45</option>
        </select>
         <select class="four columns add-bottom" required name="startTod">
          <option value="am">am</option>
          <option value="pm">pm</option>
        </select>
      </div>

      <div class="row">

        <h4> End time range</h4>
        
        <label for="hr"></label>
        <select class="four columns add-bottom" required id="hr" name="endHr">
          <option value="1">1</option>
          <option value="2">2</option>
          <option value="3">3</option>
          <option value="4">4</option>
          <option value="5">5</option>
          <option value="6">6</option>
          <option value="7">7</option>
          <option value="8">8</option>
          <option value="9">9</option>
          <option value="10">10</option>
          <option value="11">11</option>
          <option value="12">12</option>
        </select>
        <select class="four columns add-bottom" required name="endMin">
          <option value="00">00</option>
          <option value="15">15</option>
          <option value="30">30</option>
          <option value="45">45</option>
        </select>
         <select class="four columns add-bottom" required name="endTod">
          <option value="am">am</option>
          <option value="pm">pm</option>
        </select>
        </div>

        <a href="newResults.html"><div class="button full-width eight columns">Submit</div></a>
      </form> -->
  	</div>
  </body>
</html>
///////////////////
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Loc1</th>
    <th>Loc2</th>
    <th>Loc3</th>
    <th>Loc4</th>
    <th>Time1</th>
    <th>Time2</th>
    <th>Time3</th>
    <th>Time4</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.title %></td>
    <td><%= event.loc1 %></td>
    <td><%= event.loc2 %></td>
    <td><%= event.loc3 %></td>
    <td><%= event.loc4 %></td>
    <td><%= event.time1 %></td>
    <td><%= event.time2 %></td>
    <td><%= event.time3 %></td>
    <td><%= event.time4 %></td>
    <td><%= event.description %></td>
    <td><%= link_to 'Show', event %></td>
    <td><%= link_to 'Edit', edit_event_path(event) %></td>
    <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>Let's <%=@event.title%></h1>


<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @event.title %>
</p>

<p>
  <b>Loc1:</b>
  <%= @event.loc1 %>
</p>

<p>
  <b>Loc2:</b>
  <%= @event.loc2 %>
</p>

<p>
  <b>Loc3:</b>
  <%= @event.loc3 %>
</p>

<p>
  <b>Loc4:</b>
  <%= @event.loc4 %>
</p>

<p>
  <b>Time1:</b>
  <%= @event.time1 %>
</p>

<p>
  <b>Time2:</b>
  <%= @event.time2 %>
</p>

<p>
  <b>Time3:</b>
  <%= @event.time3 %>
</p>

<p>
  <b>Time4:</b>
  <%= @event.time4 %>
</p>

<p>
  <b>Description:</b>
  <%= @event.description %>
</p>


<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tueslets</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/planners/_form.html.erb
<%= form_for(@planner) do |f| %>
  <% if @planner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@planner.errors.count, "error") %> prohibited this planner from being saved:</h2>

      <ul>
      <% @planner.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password_digest %><br />
    <%= f.text_field :password_digest %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :zip %><br />
    <%= f.number_field :zip %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/planners/edit.html.erb
<h1>Editing planner</h1>

<%= render 'form' %>

<%= link_to 'Show', @planner %> |
<%= link_to 'Back', planners_path %>

app/views/planners/index.html.erb
<h1>Listing planners</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Password digest</th>
    <th>Phone</th>
    <th>Zip</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @planners.each do |planner| %>
  <tr>
    <td><%= planner.name %></td>
    <td><%= planner.email %></td>
    <td><%= planner.password_digest %></td>
    <td><%= planner.phone %></td>
    <td><%= planner.zip %></td>
    <td><%= link_to 'Show', planner %></td>
    <td><%= link_to 'Edit', edit_planner_path(planner) %></td>
    <td><%= link_to 'Destroy', planner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Planner', new_planner_path %>

app/views/planners/new.html.erb
<h1>New planner</h1>

<%= render 'form' %>

<%= link_to 'Back', planners_path %>

app/views/planners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @planner.name %>
</p>

<p>
  <b>Email:</b>
  <%= @planner.email %>
</p>

<p>
  <b>Password digest:</b>
  <%= @planner.password_digest %>
</p>

<p>
  <b>Phone:</b>
  <%= @planner.phone %>
</p>

<p>
  <b>Zip:</b>
  <%= @planner.zip %>
</p>


<%= link_to 'Edit', edit_planner_path(@planner) %> |
<%= link_to 'Back', planners_path %>